# Generated by Django 2.2.11 on 2020-06-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200607_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtersection',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='api.Video'),
        ),
    ]
